import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import { cp, readFile, rm, writeFile } from "fs/promises";
import path from "path";
import { minify } from "terser";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');
const distDir = path.resolve(process.cwd(), 'dist');

const staticAssets = [
	{ src: 'styles.css', dest: path.join('dist', 'styles.css') }
];

const cleanDistPlugin = {
	name: 'clean-dist',
	setup(build) {
		build.onStart(async () => {
			if (!prod) {
				return;
			}

			await rm(distDir, { recursive: true, force: true }).catch(() => {});
		});
	}
};

const terserMinifyPlugin = {
	name: 'terser-minify',
	setup(build) {
		build.onEnd(async (result) => {
			if (!prod || (result && result.errors && result.errors.length > 0)) {
				return;
			}

			const mainPath = path.join(distDir, 'main.js');

			try {
				const source = await readFile(mainPath, 'utf8');
				const { code } = await minify(source, {
					compress: { ecma: 2020 },
					mangle: true,
					format: {
						comments: false,
						ecma: 2020
					}
				});

				if (!code) {
					throw new Error('Terser produced empty output for dist/main.js');
				}

				await writeFile(mainPath, code, 'utf8');
				console.info('[terser] dist/main.js minified');
			} catch (error) {
				console.error('[terser] Failed to minify bundle', error);
				throw error;
			}
		});
	}
};

async function copyStaticAssets() {
	await Promise.all(staticAssets.map(async ({ src, dest }) => {
		await cp(src, dest, { recursive: true, force: true });
	}));
}

const copyStaticPlugin = {
	name: 'copy-static-assets',
	setup(build) {
		build.onEnd(async () => {
			try {
				await copyStaticAssets();
				console.info('[esbuild] Static assets copied');
			} catch (error) {
				console.error('[esbuild] Failed to copy static assets', error);
			}
		});
	}
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	define: {
		__LOG_PROD__: prod ? 'true' : 'false'
	},
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtins],
	format: 'cjs',
	target: 'es2020',
	logLevel: "info",
	minify: prod,
	legalComments: prod ? 'none' : 'eof',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'dist/main.js',
	plugins: [cleanDistPlugin, copyStaticPlugin, terserMinifyPlugin],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
