/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => TileLineBasePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// src/TableView.ts
var import_obsidian = require("obsidian");
var TABLE_VIEW_TYPE = "tile-line-base-table";
var TableView = class extends import_obsidian.ItemView {
  constructor(leaf) {
    super(leaf);
    this.file = null;
  }
  getViewType() {
    return TABLE_VIEW_TYPE;
  }
  getDisplayText() {
    var _a;
    return ((_a = this.file) == null ? void 0 : _a.basename) || "TileLineBase \u8868\u683C";
  }
  async setState(state, result) {
    const file = this.app.vault.getAbstractFileByPath(state.filePath);
    if (file instanceof import_obsidian.TFile) {
      this.file = file;
      await this.render();
    }
  }
  getState() {
    var _a;
    return {
      filePath: ((_a = this.file) == null ? void 0 : _a.path) || ""
    };
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.addClass("tile-line-base-view");
  }
  async render() {
    const container = this.containerEl.children[1];
    container.empty();
    if (!this.file) {
      container.createDiv({ text: "\u672A\u9009\u62E9\u6587\u4EF6" });
      return;
    }
    const tableContainer = container.createDiv({ cls: "tlb-table-container" });
    const content = await this.app.vault.read(this.file);
    const lines = content.split("\n");
    const table = tableContainer.createEl("table", { cls: "tlb-table" });
    const thead = table.createEl("thead");
    const headerRow = thead.createEl("tr");
    headerRow.createEl("th", { text: "\u884C\u53F7" });
    headerRow.createEl("th", { text: "\u5185\u5BB9" });
    const tbody = table.createEl("tbody");
    lines.forEach((line, index) => {
      const tr = tbody.createEl("tr");
      tr.createEl("td", { text: String(index + 1) });
      tr.createEl("td", { text: line || "(\u7A7A\u884C)" });
    });
    console.log(`TileLineBase \u8868\u683C\u89C6\u56FE\u5DF2\u52A0\u8F7D\uFF1A${this.file.path}`);
  }
  async onClose() {
  }
};

// src/main.ts
var TileLineBasePlugin = class extends import_obsidian2.Plugin {
  async onload() {
    console.log("\u52A0\u8F7D TileLineBase \u63D2\u4EF6");
    this.registerView(
      TABLE_VIEW_TYPE,
      (leaf) => new TableView(leaf)
    );
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        menu.addItem((item) => {
          item.setTitle("\u4EE5 TileLineBase \u8868\u683C\u6253\u5F00").setIcon("table").onClick(async () => {
            await this.openTableView(file);
          });
        });
      })
    );
    this.addCommand({
      id: "toggle-table-view",
      name: "\u5207\u6362 TileLineBase \u8868\u683C\u89C6\u56FE",
      checkCallback: (checking) => {
        const activeLeaf = this.app.workspace.activeLeaf;
        if (!activeLeaf)
          return false;
        if (!checking) {
          this.toggleTableView(activeLeaf);
        }
        return true;
      }
    });
  }
  async onunload() {
    console.log("\u5378\u8F7D TileLineBase \u63D2\u4EF6");
    this.app.workspace.detachLeavesOfType(TABLE_VIEW_TYPE);
  }
  async openTableView(file) {
    const { workspace } = this.app;
    const leaf = workspace.getLeaf(false);
    await leaf.setViewState({
      type: TABLE_VIEW_TYPE,
      active: true,
      state: {
        filePath: file.path
      }
    });
    workspace.revealLeaf(leaf);
  }
  async toggleTableView(leaf) {
    const currentView = leaf.view;
    if (currentView.getViewType() === TABLE_VIEW_TYPE) {
      const tableView = currentView;
      const file = tableView.file;
      if (file) {
        await leaf.setViewState({
          type: "markdown",
          state: {
            file: file.path
          }
        });
      }
    } else {
      const activeFile = this.app.workspace.getActiveFile();
      if (activeFile) {
        await leaf.setViewState({
          type: TABLE_VIEW_TYPE,
          active: true,
          state: {
            filePath: activeFile.path
          }
        });
      }
    }
  }
};
